### PR TITLE
Fixed several Warnings generated by clang-tidy and gcc

### PR DESCRIPTION
**Pull request by sven-herrmann**
New pull request, with fixed line endings. Not sure where those came from as I am solely working on Linux.
Some files not initially touched by me actually showed CRLF line endings as well.

Warnings that got fixed were int to uint conversions and a few missing member variable initializations.

### CODE REVIEW

**Comment by berndporr** [comment]
Sorry but now you have converted _all_ files to the Unix convention so that now it's even less possible for me to check where you have made changes. git diff @{1} now reports bulk changes to everything and not just the lines you have changed. Since you haven't done two commits (i.e. change to LF and then fixed the unsigned) it's impossible for me to see what you have changed as it's just one large commit. I'll change everything to unix now in the master branch but sorry cannot merge your pull request as it's not possible to track what you have done.

**Comment by sven-herrmann** [comment]
you can use --ignore-space-at-eol with git diff to ignore those

**Comment by sven-herrmann** [comment]
Additionally, --ignore-space-change ignores changes in leading white-space

**Comment by berndporr** [comment]
I've spent already far too much time on this fighting with your pull request. You need to make it in a way that it's directly applicable and not requiring commandline options etc. You need to make it as transparent and easily applicable as possible. I've spent too much time on it. Sorry!

**Pull request closed without merging**
